openapi: 3.0.0
servers:
  - url: http://localhost:3000/api
info:
  version: 1.0.2-oas3
  title: myConfix API
  description: Reference documentation for the myConfix API project.
paths:
  /hardwares:
    get:
      tags:
        - Hardwares
      description: Returns all registered hardwares
      responses:
        '200':
          description: List of all hardwares returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/Case'
                    - $ref: '#/components/schemas/Cpu'
                    - $ref: '#/components/schemas/Gpu'
                    - $ref: '#/components/schemas/Monitor'
                    - $ref: '#/components/schemas/Motherboard'
                    - $ref: '#/components/schemas/Ram'
                    - $ref: '#/components/schemas/Psu'
                    - $ref: '#/components/schemas/Storage'
        '500':
          description: Database error (cannot find hardwares)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /hardwares/{_id}:
    get:
      description: Get a hardware by ID
      tags:
        - Hardwares
      parameters:
        - in: path
          name: _id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns a specific hardware
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/Case'
                  - $ref: '#/components/schemas/Cpu'
                  - $ref: '#/components/schemas/Gpu'
                  - $ref: '#/components/schemas/Monitor'
                  - $ref: '#/components/schemas/Motherboard'
                  - $ref: '#/components/schemas/Ram'
                  - $ref: '#/components/schemas/Psu'
                  - $ref: '#/components/schemas/Storage'
        '404':
          description: Hardware with id {_id} not found!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /configs/{userId}/myconfigs:
    get:
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      tags:
        - Configs
      description: Returns all registered configurations of the user
      security:
        - authorization: []
      responses:
        '200':
          description: List of user's configurations returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Config'
        '500':
          description: Database error (cannot find configs)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      tags:
        - Configs
      description: Creates a new configuration to the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      security:
        - authorization: []
      responses:
        '201':
          description: Successfully created a new configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '500':
          description: Configuration could not be saved to the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /configs/{userId}/myconfigs/{configId}:
    get:
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
        - in: path
          name: configId
          required: true
          schema:
            type: string
      description: Get a configuration by config ID
      security:
        - authorization: []
      tags:
        - Configs
      responses:
        '200':
          description: Returns a specific configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '500':
          description: Database error (cannot find one config)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
        - in: path
          name: configId
          required: true
          schema:
            type: string
      description: Updates a configuration
      security:
        - authorization: []
      tags:
        - Configs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        '200':
          description: Config has been updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '500':
          description: Database error (could not update the config)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
        - in: path
          name: configId
          required: true
          schema:
            type: string
      description: Deletes a configuration
      security:
        - authorization: []
      tags:
        - Configs
      responses:
        '200':
          description: Config has been deleted successfully
          content:
            application/json:
              schema:
                type: object
                example: {}
        '500':
          description: Database error (cannot delete config)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users:
    get:
      description: Returns a list of users
      security:
        - authorization: []
      tags:
        - Users
      responses:
        '200':
          description: List of users returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Database error (cannot find users)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new user
      security:
        - authorization: []
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User registration has been created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: User registration failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{_id}:
    get:
      description: Get a user
      security:
        - authorization: []
      tags:
        - Users
      parameters:
        - in: path
          name: _id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid ObjectID ({_id})
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User with id {_id} not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Database error (cannot find one user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /login:
    post:
      description: Logs in a registered user
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Missing email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /logout:
    post:
      description: Logs out the user
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  description: The user's refresh token
              required:
                - refreshToken
      responses:
        '200':
          description: Successfully logged out
        '403':
          description: Forbidden request, cannot find refreshtoken
  /me:
    get:
      description: Returns logged in user's information
      tags:
        - Authorization
      security:
        - authorization: []
      responses:
        '200':
          description: Successfully returned user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  role:
                    type: string
                  _id:
                    type: string
  /refresh:
    post:
      tags:
        - Authorization
      description: Refreshes the JWT accesstoken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  description: The user's JWT refreshtoken
              required:
                - refreshToken
      responses:
        '200':
          description: Accesstoken refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: New accesstoken
        '403':
          description: Forbidden request, cannot find refreshtoken
        '404':
          description: Cannot find and refresh accesstoken
components:
  securitySchemes:
    authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Config:
      type: object
      required:
        - related_user
        - case
        - cpu
        - gpu
        - monitor
        - motherboard
        - ram
        - psu
        - storage
      properties:
        related_user:
          $ref: '#/components/schemas/User'
        case:
          $ref: '#/components/schemas/Case'
        cpu:
          $ref: '#/components/schemas/Cpu'
        gpu:
          $ref: '#/components/schemas/Gpu'
        monitor:
          $ref: '#/components/schemas/Monitor'
        motherboard:
          $ref: '#/components/schemas/Motherboard'
        ram:
          $ref: '#/components/schemas/Ram'
        psu:
          $ref: '#/components/schemas/Psu'
        storage:
          $ref: '#/components/schemas/Storage'
    Case:
      type: object
      required:
        - name
        - category
        - price_usd
      properties:
        name:
          type: string
        category:
          type: string
        price_usd:
          type: number
        type:
          type: string
        side_panel_window:
          type: string
        internal_3_5_bays:
          type: string
    Cpu:
      type: object
      required:
        - name
        - category
        - price_usd
      properties:
        name:
          type: string
        category:
          type: string
        price_usd:
          type: number
        core_clock:
          type: string
        boost_clock:
          type: string
        tdp:
          type: string
        integrated_graphics:
          nullable: true
          type: string
    Gpu:
      type: object
      required:
        - name
        - category
        - price_usd
      properties:
        name:
          type: string
        category:
          type: string
        price_usd:
          type: number
        core_clock:
          type: string
        boost_clock:
          type: string
        tdp:
          type: string
        chipset:
          type: string
    Monitor:
      type: object
      required:
        - name
        - category
        - price_usd
      properties:
        name:
          type: string
        category:
          type: string
        price_usd:
          type: number
        resolution:
          type: string
        refresh_rate:
          type: string
    Motherboard:
      type: object
      required:
        - name
        - category
        - price_usd
      properties:
        name:
          type: string
        category:
          type: string
        price_usd:
          type: number
        cpu_socket:
          type: string
        form_factor:
          type: string
        memory_max:
          type: string
        memory_slots:
          type: string
    Psu:
      type: object
      required:
        - name
        - category
        - price_usd
      properties:
        name:
          type: string
        category:
          type: string
        price_usd:
          type: number
        form_factor:
          type: string
        efficency_rating:
          type: string
        wattage:
          type: string
        modular:
          type: string
    Ram:
      type: object
      required:
        - name
        - category
        - price_usd
      properties:
        name:
          type: string
        category:
          type: string
        price_usd:
          type: number
        Speed:
          type: string
        Modules:
          type: string
    Storage:
      type: object
      required:
        - name
        - category
        - price_usd
      properties:
        name:
          type: string
        category:
          type: string
        price_usd:
          type: number
        capacity:
          type: string
        type:
          type: string
        form_factor:
          type: string
        interface:
          type: string
    User:
      type: object
      required:
        - email
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        role:
          type: string
          default: USER
        accessToken:
          type: string
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    LoginResponse:
      type: object
      required:
        - accessToken
        - refreshToken
        - user
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        user:
          type: object
          properties:
            _id:
              type: string
            role:
              type: string
              default: USER
            email:
              type: string
    Error:
      type: object
      required:
        - message
        - hasError
      properties:
        message:
          type: string
        hasError:
          type: boolean